import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Header
    'nav.features': 'Features',
    'nav.howItWorks': 'How it Works',
    'nav.reviews': 'Reviews',
    'nav.learnMore': 'Learn More',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.back': 'Back',
    'nav.search': 'Search Plants',
    
    // Hero Section
    'hero.title': 'Identify Any Plant',
    'hero.titleHighlight': 'Instantly with AI',
    'hero.subtitle': 'Take a photo and discover the name, care instructions, and fascinating details about any plant, flower, or tree in seconds.',
    'hero.tryForFree': 'Try For Free',
    'hero.watchDemo': 'Watch Demo',
    'hero.trustedBy': 'Trusted by over 2 million plant enthusiasts worldwide',
    
    // Features Section
    'features.title': 'Powerful Features for Plant Lovers',
    'features.subtitle': 'Everything you need to identify, learn about, and care for plants',
    'features.plantId': 'Instant Plant ID',
    'features.plantIdDesc': 'Identify 17,000+ plant species with 95% accuracy using advanced AI',
    'features.careGuide': 'Personalized Care',
    'features.careGuideDesc': 'Get customized care instructions for watering, lighting, and maintenance',
    'features.diseaseDetection': 'Disease Detection',
    'features.diseaseDetectionDesc': 'Spot plant diseases early and get treatment recommendations',
    'features.expertCommunity': 'Expert Community',
    'features.expertCommunityDesc': 'Connect with botanists and fellow plant enthusiasts worldwide',
    
    // How It Works Section
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Get plant insights in just a few simple steps',
    'howItWorks.step1': 'Take a Photo',
    'howItWorks.step1Desc': 'Snap or upload a picture of any plant',
    'howItWorks.step2': 'AI Analysis',
    'howItWorks.step2Desc': 'Our AI analyzes the image instantly',
    'howItWorks.step3': 'Get Results',
    'howItWorks.step3Desc': 'Receive detailed plant information and care guide',
    
    // Testimonials
    'testimonials.title': 'What Plant Lovers Say',
    'testimonials.subtitle': 'Join millions of satisfied users worldwide',
    
    // CTA Section
    'cta.title': 'Start Identifying Plants Today',
    'cta.subtitle': 'Join millions of plant enthusiasts who trust Plantify AI',
    'cta.button': 'Get Started for Free',
    
    // Footer
    'footer.description': 'The most accurate AI-powered plant identification app trusted by millions worldwide.',
    'footer.product': 'Product',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.demo': 'Demo',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.rights': '© 2024 Plantify AI. All rights reserved.',
    
    // Try For Free Page
    'tryFree.title': 'Try Plantify AI for Free',
    'tryFree.subtitle': 'Upload a photo and discover your plant instantly',
    'tryFree.uploadButton': 'Upload Photo',
    'tryFree.takePicture': 'Take Picture',
    'tryFree.analyzing': 'Analyzing your plant...',
    'tryFree.confidence': 'Confidence',
    'tryFree.scientificName': 'Scientific Name',
    'tryFree.commonNames': 'Common Names',
    'tryFree.family': 'Family',
    'tryFree.careInstructions': 'Care Instructions',
    'tryFree.tryAnother': 'Try Another Plant',
    'tryFree.dragDrop': 'Drag and drop your plant photo here, or click to select',
    'tryFree.uploadHint': 'Supports JPG, PNG files up to 10MB',
    'tryFree.plantName': 'Monstera Deliciosa',
    'tryFree.commonName': 'Swiss Cheese Plant',
    'tryFree.plantFamily': 'Araceae',
    'tryFree.wateringTitle': 'Watering',
    'tryFree.wateringDesc': 'Water when top inch of soil feels dry, typically every 1-2 weeks',
    'tryFree.lightTitle': 'Light Requirements',
    'tryFree.lightDesc': 'Bright, indirect light. Avoid direct sunlight which can scorch leaves',
    'tryFree.temperatureTitle': 'Temperature',
    'tryFree.temperatureDesc': 'Ideal range: 65-80°F (18-27°C). Protect from cold drafts',
    'tryFree.humidityTitle': 'Humidity',
    'tryFree.humidityDesc': 'Prefers 50-60% humidity. Use humidifier or pebble tray if needed',
    
    // Search Page
    'search.title': 'Plant Encyclopedia',
    'search.subtitle': 'Search our comprehensive database of plants',
    'search.placeholder': 'Search for plants by name...',
    'search.noResults': 'No plants found matching your search',
    'search.tryDifferent': 'Try different keywords or browse by category',
    'search.resultsCount': 'plant(s) found',
    'search.categories': 'Categories',
    'search.difficulty': 'Difficulty Level',
    'search.features': 'Features',
    'search.clearFilters': 'Clear Filters',
    'search.allCategories': 'All Categories',
    'search.allDifficulties': 'All Levels',
    'search.airPurifying': 'Air Purifying',
    'search.petFriendly': 'Pet Friendly',
    'search.lowLight': 'Low Light',
    'search.easyCare': 'Easy Care',
    
    // Plant Detail Page
    'plant.details': 'Plant Details',
    'plant.overview': 'Overview',
    'plant.care': 'Care Guide',
    'plant.characteristics': 'Characteristics',
    'plant.facts': 'Interesting Facts',
    'plant.benefits': 'Benefits',
    'plant.toxicity': 'Toxicity Information',
    'plant.propagation': 'Propagation',
    'plant.problems': 'Common Problems',
    'plant.scientificName': 'Scientific Name',
    'plant.commonNames': 'Common Names',
    'plant.family': 'Plant Family',
    'plant.category': 'Category',
    'plant.difficulty': 'Difficulty Level',
    'plant.origin': 'Origin',
    'plant.height': 'Height',
    'plant.spread': 'Spread',
    'plant.bloomTime': 'Bloom Time',
    'plant.hardiness': 'Hardiness Zone',
    'plant.watering': 'Watering',
    'plant.light': 'Light Requirements',
    'plant.temperature': 'Temperature',
    'plant.humidity': 'Humidity',
    'plant.soil': 'Soil',
    'plant.fertilizer': 'Fertilizer',
    'plant.airPurifyingYes': 'Excellent air purifier',
    'plant.airPurifyingNo': 'Not specifically air purifying',
    'plant.petFriendlyYes': 'Safe for pets',
    'plant.petFriendlyNo': 'Keep away from pets',
    'plant.addToWishlist': 'Add to Wishlist',
    'plant.shareLink': 'Share Plant',
    'plant.printGuide': 'Print Care Guide',
    
    // Demo Page
    'demo.title': 'See Plantify AI in Action',
    'demo.subtitle': 'Watch how our AI identifies plants in real-time',
    'demo.watchVideo': 'Watch Demo Video',
    'demo.tryNow': 'Try It Now',
    'demo.videoPlaying': 'Demo video playing...',
    'demo.videoComplete': 'Demo completed! Ready to try it yourself?',
    'demo.featuresTitle': 'Key Features Demonstration',
    'demo.instantId': 'Instant Identification',
    'demo.instantIdDesc': 'See how quickly our AI can identify any plant',
    'demo.accurateResults': 'Accurate Results',
    'demo.accurateResultsDesc': 'Get scientific names and confidence scores',
    'demo.careGuide': 'Care Instructions',
    'demo.careGuideDesc': 'Receive detailed care recommendations',
    
    // Learn More Page
    'learnMore.title': 'Advanced AI Plant Recognition',
    'learnMore.subtitle': 'Discover the technology behind accurate plant identification',
    'learnMore.aiTechnology': 'AI Technology',
    'learnMore.aiDesc': 'Our deep learning models are trained on millions of plant images',
    'learnMore.accuracy': 'Accuracy & Speed',
    'learnMore.accuracyDesc': '95%+ identification accuracy in under 5 seconds',
    'learnMore.database': 'Comprehensive Database',
    'learnMore.databaseDesc': 'Over 17,000 plant species from around the world',
    'learnMore.experts': 'Expert Validation',
    'learnMore.expertsDesc': 'Results validated by professional botanists',
    
    // Reviews Page
    'reviews.title': 'User Reviews & Ratings',
    'reviews.subtitle': 'See what plant lovers are saying about Plantify AI',
    'reviews.overallRating': 'Overall Rating',
    'reviews.totalReviews': 'Based on 50,000+ reviews',
    'reviews.writeReview': 'Write a Review',
    'reviews.filterAll': 'All Reviews',
    'reviews.filter5Star': '5 Stars',
    'reviews.filter4Star': '4 Stars',
    'reviews.filter3Star': '3 Stars',
    'reviews.ratingBreakdown': 'Rating Breakdown',
    'reviews.verified': 'Verified Purchase',
    'reviews.helpful': 'Helpful',
    
    // How It Works Page
    'howItWorksPage.title': 'How Plantify AI Identifies Plants',
    'howItWorksPage.subtitle': 'Discover the simple 4-step process that powers accurate plant identification',
    'howItWorksPage.tryNow': 'Try It Now',
    'howItWorksPage.processTab': 'Process',
    'howItWorksPage.technologyTab': 'Technology',
    'howItWorksPage.featuresTab': 'Features',
    'howItWorksPage.faqTab': 'FAQ',
    'howItWorksPage.step1Title': 'Take a Photo',
    'howItWorksPage.step1Subtitle': 'Capture or Upload',
    'howItWorksPage.step1Desc': 'Simply snap a photo of any plant using your camera or upload from gallery',
    'howItWorksPage.step2Title': 'AI Analysis',
    'howItWorksPage.step2Subtitle': 'Advanced Processing',
    'howItWorksPage.step2Desc': 'Our AI analyzes the image using deep learning algorithms',
    'howItWorksPage.step3Title': 'Instant Results',
    'howItWorksPage.step3Subtitle': 'Accurate Identification',
    'howItWorksPage.step3Desc': 'Get comprehensive plant information and confidence score',
    'howItWorksPage.step4Title': 'Care Guide',
    'howItWorksPage.step4Subtitle': 'Expert Advice',
    'howItWorksPage.step4Desc': 'Receive detailed care instructions and growing tips',
    
    // Features Page
    'featuresPage.title': 'Powerful Features for Plant Lovers',
    'featuresPage.subtitle': 'Discover all the tools you need to identify, care for, and learn about plants',
    'featuresPage.tryAllFeatures': 'Try All Features Free',
    'featuresPage.comparePlans': 'Compare Plans',
    'featuresPage.overviewTab': 'Overview',
    'featuresPage.detailedTab': 'Detailed View',
    'featuresPage.technicalTab': 'Technical',
    'featuresPage.comparisonTab': 'Plans',
    'featuresPage.plantIdentification': 'Plant Identification',
    'featuresPage.personalizedCare': 'Personalized Care Guide',
    'featuresPage.diseaseDetection': 'Disease Detection',
    'featuresPage.smartReminders': 'Smart Reminders',
    'featuresPage.expertCommunity': 'Expert Community',
    'featuresPage.offlineMode': 'Offline Capability',
    
    // Language Selector
    'language.select': 'Language',
    'language.english': 'English',
    'language.hindi': 'हिन्दी',
    'language.bengali': 'বাংলা',
    
    // Sign In Page
    'signIn.title': 'Welcome Back',
    'signIn.subtitle': 'Sign in to your Plantify AI account',
    'signIn.emailLabel': 'Email',
    'signIn.emailPlaceholder': 'Enter your email',
    'signIn.passwordLabel': 'Password',
    'signIn.passwordPlaceholder': 'Enter your password',
    'signIn.rememberMe': 'Remember me',
    'signIn.signInButton': 'Sign In',
    'signIn.forgotPassword': 'Forgot your password?',
    'signIn.noAccount': 'Don\'t have an account?',
    'signIn.createAccount': 'Create one now',
    'signIn.orContinueWith': 'Or continue with',
    'signIn.googleSignIn': 'Continue with Google',
    'signIn.appleSignIn': 'Continue with Apple',
    'signIn.githubSignIn': 'Continue with GitHub',
    'signIn.signingIn': 'Signing in...',
    'signIn.invalidCredentials': 'Invalid email or password',
    'signIn.welcomeBack': 'Welcome back!',
    'signIn.backToHome': 'Back to Home',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.readMore': 'Read More',
    'common.showMore': 'Show More',
    'common.showLess': 'Show Less',
    'common.viewAll': 'View All',
  },
  
  hi: {
    // Header
    'nav.features': 'विशेषताएं',
    'nav.howItWorks': 'यह कैसे काम करता है',
    'nav.reviews': 'समीक्षाएं',
    'nav.learnMore': 'और जानें',
    'nav.signIn': 'साइन इन',
    'nav.getStarted': 'शुरू करें',
    'nav.back': 'वापस',
    'nav.search': 'पौधे खोजें',
    
    // Hero Section
    'hero.title': 'किसी भी पौधे की पहचान करें',
    'hero.titleHighlight': 'AI के साथ तुरंत',
    'hero.subtitle': 'एक फोटो लें और सेकंडों में किसी भी पौधे, फूल या पेड़ का नाम, देखभाल के निर्देश और दिलचस्प विवरण जानें।',
    'hero.tryForFree': 'मुफ्त में आजमाएं',
    'hero.watchDemo': 'डेमो देखें',
    'hero.trustedBy': 'दुनिया भर के 20 लाख से अधिक पौधे प्रेमियों का भरोसा',
    
    // Features Section
    'features.title': 'पौधे प्रेमियों के लिए शक्तिशाली विशेषताएं',
    'features.subtitle': 'पौधों की पहचान, उनके बारे में जानने और उनकी देखभाल के लिए सब कुछ',
    'features.plantId': 'तत्काल पौधा पहचान',
    'features.plantIdDesc': 'उन्नत AI का उपयोग करके 95% सटीकता के साथ 17,000+ पौधों की प्रजातियों की पहचान करें',
    'features.careGuide': 'व्यक्तिगत देखभाल',
    'features.careGuideDesc': 'पानी, प्रकाश और रखरखाव के लिए अनुकूलित देखभाल निर्देश प्राप्त करें',
    'features.diseaseDetection': 'रोग का पता लगाना',
    'features.diseaseDetectionDesc': 'पौधों की बीमारियों की जल्दी पहचान करें और इलाज की सिफारिशें प्राप्त करें',
    'features.expertCommunity': 'विशेषज्ञ समुदाय',
    'features.expertCommunityDesc': 'दुनिया भर के वनस्पति विज्ञानियों और पौधे प्रेमियो�� से जुड़ें',
    
    // How It Works Section
    'howItWorks.title': 'यह कैसे काम करता है',
    'howItWorks.subtitle': 'केवल कुछ सरल चरणों में पौधे की जानकारी प्राप्त करें',
    'howItWorks.step1': 'फोटो लें',
    'howItWorks.step1Desc': 'किसी भी पौधे की तस्वीर लें या अपलोड करें',
    'howItWorks.step2': 'AI विश्लेषण',
    'howItWorks.step2Desc': 'हमारा AI तुरंत छवि का विश्लेषण करता है',
    'howItWorks.step3': 'परिणाम प्राप्त करें',
    'howItWorks.step3Desc': 'विस्तृत पौधे की जानकारी और देखभाल गाइड प्राप्त करें',
    
    // Testimonials
    'testimonials.title': 'पौधे प्रेमी क्या कहते हैं',
    'testimonials.subtitle': 'दुनिया भर के लाखों संतुष्ट उपयोगकर्ताओं से जुड़ें',
    
    // CTA Section
    'cta.title': 'आज ही पौधों की पहचान करना शुरू करें',
    'cta.subtitle': 'लाखों पौधे प्रेमियों में शामिल हों जो Plantify AI पर भरोसा करते हैं',
    'cta.button': 'मुफ्त में शुरू करें',
    
    // Footer
    'footer.description': 'दुनिया भर के लाखों लोगों द्वारा भरोसा की जाने वाली सबसे सटीक AI-संचालित पौधा पहचान ऐप।',
    'footer.product': 'उत्पाद',
    'footer.features': 'विशेषताएं',
    'footer.pricing': 'मूल्य निर्धारण',
    'footer.demo': 'डेमो',
    'footer.company': 'कंपनी',
    'footer.about': 'के बारे में',
    'footer.blog': 'ब्लॉग',
    'footer.careers': 'करियर',
    'footer.support': 'सहायता',
    'footer.help': 'सहायता केंद्र',
    'footer.contact': 'संपर्क',
    'footer.privacy': 'गोपनीयता',
    'footer.terms': 'शर्तें',
    'footer.rights': '© 2024 Plantify AI. सभी अधिकार सुरक्षित।',
    
    // Try For Free Page
    'tryFree.title': 'Plantify AI को मुफ्त में आजमाएं',
    'tryFree.subtitle': 'एक फोटो अपलोड करें और अपने पौध�� को तुरंत जानें',
    'tryFree.uploadButton': 'फोटो अपलोड करें',
    'tryFree.takePicture': 'तस्वीर लें',
    'tryFree.analyzing': 'आपके पौधे का विश्लेषण कर रहे हैं...',
    'tryFree.confidence': 'विश्वास',
    'tryFree.scientificName': 'वैज्ञानिक नाम',
    'tryFree.commonNames': 'सामान्य नाम',
    'tryFree.family': 'परिवार',
    'tryFree.careInstructions': 'देखभाल निर्देश',
    'tryFree.tryAnother': 'अन्य पौधा आजमाएं',
    'tryFree.dragDrop': 'अपनी पौधे की फोटो यहाँ खींचें और छोड़ें, या चुनने के लिए क्लिक करें',
    'tryFree.uploadHint': '10MB तक JPG, PNG फाइलों का समर्थन करता है',
    'tryFree.plantName': 'मॉन्स्टेरा डेलिसिओसा',
    'tryFree.commonName': 'स्विस चीज़ प्लांट',
    'tryFree.plantFamily': 'एरेसी',
    'tryFree.wateringTitle': 'पानी देना',
    'tryFree.wateringDesc': 'जब मिट्टी का ऊपरी हिस्सा सूखा लगे तो पानी दें, आमत��र पर हर 1-2 सप्ताह में',
    'tryFree.lightTitle': 'प्रकाश आवश्यकताएं',
    'tryFree.lightDesc': 'तेज़, अप्रत्यक्ष प्रकाश। सीधी धूप से बचें जो पत्तियों को जला सकती है',
    'tryFree.temperatureTitle': 'तापमान',
    'tryFree.temperatureDesc': 'आदर्श सीमा: 65-80°F (18-27°C)। ठंडी हवा से बचाएं',
    'tryFree.humidityTitle': 'नमी',
    'tryFree.humidityDesc': '50-60% नमी पसंद करता है। यदि आवश्यक हो तो ह्यूमिडिफायर या कंकड़ ट्रे का उपयोग करें',
    
    // Search Page
    'search.title': 'पौधों का विश्वकोश',
    'search.subtitle': 'हमारे पौधों के व्यापक डेटाबेस में खोजें',
    'search.placeholder': 'नाम से पौधे खोजें...',
    'search.noResults': 'आपकी खोज से मेल खाने वाले कोई पौधे नहीं मिले',
    'search.tryDifferent': 'अलग कीवर्ड आज़माएं या श्रेणी के अनुसार ब्राउज़ करें',
    'search.resultsCount': 'पौधे मिले',
    'search.categories': 'श्रेणियां',
    'search.difficulty': 'कठिनाई स्तर',
    'search.features': 'विशेषताएं',
    'search.clearFilters': 'फ़िल्टर साफ़ करें',
    'search.allCategories': 'सभी श्रेणियां',
    'search.allDifficulties': 'सभी स्तर',
    'search.airPurifying': 'वायु शुद्धीकरण',
    'search.petFriendly': 'पालतू-अनुकूल',
    'search.lowLight': 'कम रोशनी',
    'search.easyCare': 'आसान देखभाल',
    
    // Plant Detail Page
    'plant.details': 'पौधे का विवरण',
    'plant.overview': 'अवलोकन',
    'plant.care': 'देखभाल गाइड',
    'plant.characteristics': 'विशेषताएं',
    'plant.facts': 'दिलचस्प तथ्य',
    'plant.benefits': 'लाभ',
    'plant.toxicity': 'विषाक्तता की जानकारी',
    'plant.propagation': 'प्रसार',
    'plant.problems': 'सामान्य समस्याएं',
    'plant.scientificName': 'वैज्ञानिक नाम',
    'plant.commonNames': 'सामान्य नाम',
    'plant.family': 'पौधे का परिवा��',
    'plant.category': 'श्रेणी',
    'plant.difficulty': 'कठिनाई स्तर',
    'plant.origin': 'मूल',
    'plant.height': 'ऊंचाई',
    'plant.spread': 'फैलाव',
    'plant.bloomTime': 'फूल का समय',
    'plant.hardiness': 'कठोरता क्षेत्र',
    'plant.watering': 'पानी देना',
    'plant.light': 'प्रकाश आवश्यकताएं',
    'plant.temperature': 'तापमान',
    'plant.humidity': 'नमी',
    'plant.soil': 'मिट्टी',
    'plant.fertilizer': 'उर्वरक',
    'plant.airPurifyingYes': 'उत्कृष्ट वायु शुद्धक',
    'plant.airPurifyingNo': 'विशेष रूप से वायु शुद्धीकरण नहीं',
    'plant.petFriendlyYes': 'पालतू जानवरों के लिए सुरक्षित',
    'plant.petFriendlyNo': 'पालतू जानवरों से दूर रखें',
    'plant.addToWishlist': 'विशलिस्ट में जोड़ें',
    'plant.shareLink': 'पौधा साझा करें',
    'plant.printGuide': 'देखभाल गाइड प्रिंट करें',
    
    // Demo Page
    'demo.title': 'Plantify AI को कार्य में देखें',
    'demo.subtitle': 'देखें कि हमारा AI वास्तविक समय में पौधों की पहचान कैसे करता है',
    'demo.watchVideo': 'डेमो वीडियो देखें',
    'demo.tryNow': 'अभी आज़माएं',
    'demo.videoPlaying': 'डेमो वीडियो चल रहा है...',
    'demo.videoComplete': 'डेमो पूरा हुआ! अब खुद आज़माने के लिए तैयार हैं?',
    'demo.featuresTitle': 'मुख्य विशेषताओं का प्रदर्शन',
    'demo.instantId': 'तत्काल पहचान',
    'demo.instantIdDesc': 'देखें कि हमारा AI कितनी जल्दी किसी भी पौधे की पहचान कर सकता है',
    'demo.accurateResults': 'सटीक परिणाम',
    'demo.accurateResultsDesc': 'वैज्ञानिक नाम और विश्वास स्कोर प्राप्त करें',
    'demo.careGuide': 'देखभाल निर्देश',
    'demo.careGuideDesc': 'विस्तृत देखभाल सिफारिशें प्राप्त करें',
    
    // Learn More Page
    'learnMore.title': 'उन्नत AI पौधा पहचान',
    'learnMore.subtitle': 'सटीक पौधा पहचान के पीछे की तकनीक जानें',
    'learnMore.aiTechnology': 'AI तकनीक',
    'learnMore.aiDesc': 'हमारे गहन शिक्षण मॉडल लाखों पौधों की छवियों पर प्रशिक्षित हैं',
    'learnMore.accuracy': 'सटीकता और गति',
    'learnMore.accuracyDesc': '5 सेकंड से कम में 95%+ पहचान सटीकता',
    'learnMore.database': 'व्यापक डेटाबेस',
    'learnMore.databaseDesc': 'दुनिया भर से 17,000 से अधिक पौधों की प्रजातियां',
    'learnMore.experts': 'विशेषज्ञ सत्यापन',
    'learnMore.expertsDesc': 'पेशेवर वनस्पति विज्ञानियों द्वारा सत्यापित परिणाम',
    
    // Reviews Page
    'reviews.title': 'उपयोगकर्ता समीक्षा और रेटिंग',
    'reviews.subtitle': 'देखें कि पौधे प्रेमी Plantify AI के बारे में क्या कह रहे हैं',
    'reviews.overallRating': 'समग्र रेटिंग',
    'reviews.totalReviews': '50,000+ समीक्���ाओं के आधार पर',
    'reviews.writeReview': 'एक समीक्षा लिखें',
    'reviews.filterAll': 'सभी समीक्षाएं',
    'reviews.filter5Star': '5 सितारे',
    'reviews.filter4Star': '4 सितारे',
    'reviews.filter3Star': '3 सितारे',
    'reviews.ratingBreakdown': 'रेटिंग विवरण',
    'reviews.verified': 'सत्यापित खरीदारी',
    'reviews.helpful': 'उपयोगी',
    
    // How It Works Page
    'howItWorksPage.title': 'Plantify AI पौधों की पहचान कैसे करता है',
    'howItWorksPage.subtitle': 'सटीक पौधा पहचान को संचालित करने वाली सरल 4-चरणीय प्रक्रिया जानें',
    'howItWorksPage.tryNow': 'अभी आज़माएं',
    'howItWorksPage.processTab': 'प्रक्रिया',
    'howItWorksPage.technologyTab': 'तकनीक',
    'howItWorksPage.featuresTab': 'विशेषताएं',
    'howItWorksPage.faqTab': 'FAQ',
    'howItWorksPage.step1Title': 'फोटो लें',
    'howItWorksPage.step1Subtitle': 'कैप्चर या अपलोड',
    'howItWorksPage.step1Desc': 'बस अपने कैमरे का उपयोग करके कि��ी भी पौधे की फोटो लें या गैलरी से अपलोड करें',
    'howItWorksPage.step2Title': 'AI विश्लेषण',
    'howItWorksPage.step2Subtitle': 'उन्नत प्रसंस्करण',
    'howItWorksPage.step2Desc': 'हमारा AI गहन शिक्षण एल्गोरिदम का उपयोग करके छवि का विश्लेषण करता है',
    'howItWorksPage.step3Title': 'तत्काल परिणाम',
    'howItWorksPage.step3Subtitle': 'सटीक पहचान',
    'howItWorksPage.step3Desc': 'व्यापक पौधे की जानकारी और विश्वास स्कोर प्राप्त करें',
    'howItWorksPage.step4Title': 'देखभाल गाइड',
    'howItWorksPage.step4Subtitle': 'विशेषज्ञ सलाह',
    'howItWorksPage.step4Desc': 'विस्तृत देखभाल निर्देश और बढ़ने की सुझाव प्राप्त करें',
    
    // Features Page
    'featuresPage.title': 'पौधे प्रेमियों के लिए शक्तिशाली विशेषताएं',
    'featuresPage.subtitle': 'पौधों की पहचान, देखभाल और सीखने के लिए आवश्यक सभी उपकरण खोजें',
    'featuresPage.tryAllFeatures': 'सभी सुविधाएं मुफ्त में आजमाएं',
    'featuresPage.comparePlans': 'योजनाओं की तुलना करें',
    'featuresPage.overviewTab': 'अवलोकन',
    'featuresPage.detailedTab': 'विस्तृत दृश्य',
    'featuresPage.technicalTab': 'तकनीकी',
    'featuresPage.comparisonTab': 'योजनाएं',
    'featuresPage.plantIdentification': 'पौधा पहचान',
    'featuresPage.personalizedCare': 'व्यक्तिगत देखभाल गाइड',
    'featuresPage.diseaseDetection': 'रोग का पता लगाना',
    'featuresPage.smartReminders': 'स्मार्ट रिमाइंडर',
    'featuresPage.expertCommunity': 'विशेषज्ञ समुदाय',
    'featuresPage.offlineMode': 'ऑफ़लाइन क्षमता',
    
    // Language Selector
    'language.select': 'भाषा',
    'language.english': 'English',
    'language.hindi': 'हिन्दी',
    'language.bengali': 'বাংলা',
    
    // Sign In Page
    'signIn.title': 'वापसी पर स्वागत',
    'signIn.subtitle': 'अपने Plantify AI खाते में साइन इन करें',
    'signIn.emailLabel': 'ईमेल',
    'signIn.emailPlaceholder': 'अपना ईमेल दर्ज करें',
    'signIn.passwordLabel': 'पासवर्ड',
    'signIn.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
    'signIn.rememberMe': 'मुझे याद रखें',
    'signIn.signInButton': 'साइन इन',
    'signIn.forgotPassword': 'अपना पासवर्ड भूल गए?',
    'signIn.noAccount': 'कोई खाता नहीं है?',
    'signIn.createAccount': 'अभी एक बनाएं',
    'signIn.orContinueWith': 'या इसके साथ जारी रखें',
    'signIn.googleSignIn': 'Google के साथ जारी रखें',
    'signIn.appleSignIn': 'Apple के साथ जारी रखें',
    'signIn.githubSignIn': 'GitHub के साथ जारी रखें',
    'signIn.signingIn': 'साइन इन हो रहा है...',
    'signIn.invalidCredentials': 'अमान्य ईमेल या पासवर्ड',
    'signIn.welcomeBack': 'वापसी पर स्वागत!',
    'signIn.backToHome': 'होम पर वापस',

    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.save': 'सेव करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'मिटाएं',
    'common.close': 'बंद करें',
    'common.readMore': 'और पढ़ें',
    'common.showMore': 'और दिखाएं',
    'common.showLess': 'कम दिखाएं',
    'common.viewAll': 'सभी देखें',
  },
  
  bn: {
    // Header
    'nav.features': 'বৈশিষ্ট্য',
    'nav.howItWorks': 'এটি কীভাবে কাজ করে',
    'nav.reviews': 'পর্যালোচনা',
    'nav.learnMore': 'আরও জানুন',
    'nav.signIn': 'সাইন ইন',
    'nav.getStarted': 'শুরু করুন',
    'nav.back': 'পিছনে',
    'nav.search': 'গাছ খুঁজুন',
    
    // Hero Section
    'hero.title': 'যেকোনো গাছের পরিচয় জানুন',
    'hero.titleHighlight': 'AI দিয়ে তাৎক্ষণিক',
    'hero.subtitle': 'একটি ফটো তুলুন এবং সেকেন্ডের মধ্যে যেকোনো গাছ, ফুল বা গাছের নাম, যত্নের নির্দেশাবলী এবং আকর্ষণীয় বিবরণ আবিষ্কার করুন।',
    'hero.tryForFree': 'বিনামূল্যে চেষ্টা করুন',
    'hero.watchDemo': 'ডেমো দেখুন',
    'hero.trustedBy': 'বিশ্বব্যাপী ২০ লক্ষেরও বেশি উদ্ভিদ প্রেমিকদের বিশ্বস্ত',
    
    // Features Section
    'features.title': 'উদ্ভিদ প্রেমীদের জন্য শক্তিশালী বৈশিষ্ট্য',
    'features.subtitle': 'উদ্ভিদ শনাক্তকরণ, শেখা এবং যত্ন নেওয়ার জন্য যা কিছু প্রয়োজন',
    'features.plantId': 'তাৎক্ষণিক উদ্ভিদ শনাক্তকরণ',
    'features.plantIdDesc': 'উন্নত AI ব্যবহার করে ৯৫% নির্ভুলতার সাথে ১৭,০০০+ উদ্ভিদ প্রজাতি শনাক্ত করুন',
    'features.careGuide': 'ব্যক্তিগতকৃত যত্ন',
    'features.careGuideDesc': 'পানি, আলো এবং রক্ষণাবেক্ষণের জন্য কাস্টমাইজড যত্ন নির্দেশাবলী পান',
    'features.diseaseDetection': 'রোগ নির��ণয়',
    'features.diseaseDetectionDesc': 'উদ্ভিদের রোগ তাড়াতাড়ি শনাক্ত করুন এবং চিকিৎসার পরামর্শ পান',
    'features.expertCommunity': 'বিশেষজ্ঞ সম্প্রদায়',
    'features.expertCommunityDesc': 'বিশ্বব্যাপী উদ্ভিদবিদ এবং উদ্ভিদ প্রেমীদের সাথে সংযুক্ত হন',
    
    // How It Works Section
    'howItWorks.title': 'এটি কীভাবে কাজ করে',
    'howItWorks.subtitle': 'মাত্র কয়েকটি সহজ ধাপে উদ্ভিদের তথ্য পান',
    'howItWorks.step1': 'ফটো তুলুন',
    'howItWorks.step1Desc': 'যেকোনো উদ্ভিদের ছবি তুলুন বা আপলোড করুন',
    'howItWorks.step2': 'AI বিশ্লেষণ',
    'howItWorks.step2Desc': 'আমাদের AI তাৎক্ষণিকভাবে ছবি বিশ্লেষণ করে',
    'howItWorks.step3': 'ফলাফল পান',
    'howItWorks.step3Desc': 'বিস্তারিত উদ্ভিদের তথ্য এবং যত্ন গাইড গ্রহণ করুন',
    
    // Testimonials
    'testimonials.title': 'উদ্ভিদ প্রেমীরা কী বলেন',
    'testimonials.subtitle': 'বিশ্বব্যাপী লক্ষ লক্ষ সন্তুষ্ট ব্যবহারকারীদের সাথে যোগ দিন',
    
    // CTA Section
    'cta.title': 'আজই উদ্ভিদ শনাক্তকরণ শুরু করুন',
    'cta.subtitle': 'লক্ষ লক্ষ উদ্ভিদ প্রেমীর সাথে যোগ দিন যারা Plantify AI-কে বিশ্বাস করেন',
    'cta.button': 'বিনামূল্যে শুরু করুন',
    
    // Footer
    'footer.description': 'বিশ্বব্যাপী লক্ষ লক্ষ মানুষের বিশ্বস্ত সবচেয়ে নির্ভুল AI-চালিত উদ্ভিদ শনাক্তকরণ অ্যাপ।',
    'footer.product': 'পণ্য',
    'footer.features': 'বৈশিষ্ট্য',
    'footer.pricing': 'মূল্য',
    'footer.demo': 'ডেমো',
    'footer.company': 'কোম্পানি',
    'footer.about': 'সম্পর্কে',
    'footer.blog': 'ব্লগ',
    'footer.careers': 'ক্যারিয়ার',
    'footer.support': 'সহায়তা',
    'footer.help': 'সহায়তা কেন্দ্র',
    'footer.contact': 'যোগাযোগ',
    'footer.privacy': 'গোপনীয়তা',
    'footer.terms': 'শর্তাবলী',
    'footer.rights': '© ২০২৪ Plantify AI. সকল অধিকার সংরক্ষিত।',
    
    // Try For Free Page
    'tryFree.title': 'Plantify AI বিনামূল্যে চেষ্টা করুন',
    'tryFree.subtitle': 'একটি ফটো আপলোড করুন এবং আপনার উদ্ভিদ তাৎক্ষণিকভাবে আবিষ্কার করুন',
    'tryFree.uploadButton': 'ফটো আপলোড করুন',
    'tryFree.takePicture': 'ছবি তুলুন',
    'tryFree.analyzing': 'আপনার উদ্ভিদ বিশ্লেষণ করা হচ্ছে...',
    'tryFree.confidence': 'আত্মবিশ্বাস',
    'tryFree.scientificName': 'বৈজ্ঞানিক নাম',
    'tryFree.commonNames': 'সাধারণ নাম',
    'tryFree.family': 'পরিবার',
    'tryFree.careInstructions': 'যত্ন নির্দেশাবলী',
    'tryFree.tryAnother': 'অন্য উদ্ভিদ চেষ্টা করুন',
    'tryFree.dragDrop': 'আপনার উদ্ভিদের ফটো এখানে টেনে এনে ছাড়ুন, অথবা নির্বাচন করতে ক্লিক করুন',
    'tryFree.uploadHint': '১০MB পর্যন্ত JPG, PNG ফাইল সমর্থিত',
    'tryFree.plantName': 'মনস্টেরা ডেলিসিওসা',
    'tryFree.commonName': 'সুইস চিজ প্লান্ট',
    'tryFree.plantFamily': 'অ্যারেসি',
    'tryFree.wateringTitle': 'পানি দেওয়া',
    'tryFree.wateringDesc': 'মাটির উপরের অংশ শুকনো মনে হলে পানি দিন, সাধারণত প্রতি ১-২ সপ্তাহে',
    'tryFree.lightTitle': 'আলোর প্রয়োজনীয়তা',
    'tryFree.lightDesc': 'উজ্জ্বল, পরোক্ষ আলো। সরাসরি সূর্যের আলো এড়িয়ে চলুন যা পাতা পুড়িয়ে দিতে পারে',
    'tryFree.temperatureTitle': 'তাপমাত্রা',
    'tryFree.temperatureDesc': 'আদর্শ পরিসর: ৬৫-৮০°F (১৮-২৭°C)। ঠান্ডা বাতাস থেকে রক্ষা করুন',
    'tryFree.humidityTitle': 'আর্দ্রতা',
    'tryFree.humidityDesc': '৫০-৬০% আর্দ্রতা পছন্দ করে। প্রয়োজনে হিউমিডিফায়ার ���া নুড়ির ট্রে ব্যবহার করুন',
    
    // Search Page
    'search.title': 'উদ্ভিদ বিশ্বকোষ',
    'search.subtitle': 'আমাদের উদ্ভিদের বিস্তৃত ডেটাবেসে অনুসন্ধান করুন',
    'search.placeholder': 'নাম দিয়ে উদ্ভিদ খুঁজুন...',
    'search.noResults': 'আপনার অনুসন্ধানের সাথে মিলছে এমন কোনো উদ্ভিদ পাওয়া যায়নি',
    'search.tryDifferent': 'ভিন্ন কীওয়ার্ড চেষ্টা করুন বা বিভাগ অনুযায়ী ব্রাউজ করুন',
    'search.resultsCount': 'টি উদ্ভিদ পাওয়া গেছে',
    'search.categories': 'বিভাগসমূহ',
    'search.difficulty': 'কঠিনতার স্তর',
    'search.features': 'বৈশিষ্ট্য',
    'search.clearFilters': 'ফিল্টার সাফ করুন',
    'search.allCategories': 'সব বিভাগ',
    'search.allDifficulties': 'সব স্তর',
    'search.airPurifying': 'বায়ু পরিশোধক',
    'search.petFriendly': 'পোষা প্রাণী বান্ধব',
    'search.lowLight': 'ক��� আলো',
    'search.easyCare': 'সহজ যত্ন',
    
    // Plant Detail Page
    'plant.details': 'উদ্ভিদের বিবরণ',
    'plant.overview': 'সংক্ষিপ্ত বিবরণ',
    'plant.care': 'যত্ন গাইড',
    'plant.characteristics': 'বৈশিষ্ট্য',
    'plant.facts': 'আকর্ষণীয় তথ্য',
    'plant.benefits': 'উপকারিতা',
    'plant.toxicity': 'বিষাক্ততার তথ্য',
    'plant.propagation': 'বংশবিস্তার',
    'plant.problems': 'সাধারণ সমস্যা',
    'plant.scientificName': 'বৈজ্ঞানিক নাম',
    'plant.commonNames': 'সাধারণ নাম',
    'plant.family': 'উদ্ভিদ পরিবার',
    'plant.category': 'বিভাগ',
    'plant.difficulty': 'কঠিনতার স্তর',
    'plant.origin': 'উৎপত্তিস্থল',
    'plant.height': 'উচ্চতা',
    'plant.spread': 'বিস্তার',
    'plant.bloomTime': 'ফুল ফোটার সময়',
    'plant.hardiness': 'দৃঢ়তা অঞ্চল',
    'plant.watering': 'পানি দেওয়া',
    'plant.light': 'আলোর প্রয়োজনীয়তা',
    'plant.temperature': 'তাপমাত্রা',
    'plant.humidity': 'আর্দ্রতা',
    'plant.soil': 'মাটি',
    'plant.fertilizer': 'সার',
    'plant.airPurifyingYes': 'চমৎকার বায়ু পরিশোধক',
    'plant.airPurifyingNo': 'বিশেষভাবে বায়ু পরিশোধক নয়',
    'plant.petFriendlyYes': 'পোষা প্রাণীদের জন্য নিরাপদ',
    'plant.petFriendlyNo': 'পোষা প্রাণী থেকে দূরে রাখুন',
    'plant.addToWishlist': 'ইচ্ছা তালিকায় যোগ করুন',
    'plant.shareLink': 'উদ্ভিদ শেয়ার করুন',
    'plant.printGuide': 'যত্ন গাইড প্রিন্ট করুন',
    
    // Demo Page
    'demo.title': 'Plantify AI কে কাজে দেখুন',
    'demo.subtitle': 'দেখুন কিভাবে আমাদের AI রিয়েল-টাইমে উদ্ভিদ শনাক্ত করে',
    'demo.watchVideo': 'ডেমো ভিডিও দেখুন',
    'demo.tryNow': 'এখনই চেষ্টা করুন',
    'demo.videoPlaying': 'ডেমো ভিডিও চলছে...',
    'demo.videoComplete': 'ডেমো সম্পন্ন! এখন নিজে চেষ্টা করার জন্য প্রস্তুত?',
    'demo.featuresTitle': 'প্রধান বৈশিষ্ট্যের প্রদর্শনী',
    'demo.instantId': 'তাৎক্ষণিক শনাক্তকরণ',
    'demo.instantIdDesc': 'দেখুন কত দ্রুত আমাদের AI যেকোনো উদ্ভিদ শনাক্ত করতে পারে',
    'demo.accurateResults': 'নির্ভুল ফলাফল',
    'demo.accurateResultsDesc': 'বৈজ্ঞানিক নাম এবং আত্মবিশ্বাসের স্কোর পান',
    'demo.careGuide': 'যত্ন নির্দেশাবলী',
    'demo.careGuideDesc': 'বিস্তারিত যত্নের সুপারিশ গ্রহণ করুন',
    
    // Learn More Page
    'learnMore.title': 'উন্নত AI উদ্ভিদ চিনতে পারা',
    'learnMore.subtitle': 'নির্ভুল উদ্ভিদ শনাক্তকরণের পিছনের প্রযুক্তি আবিষ্কার করুন',
    'learnMore.aiTechnology': 'AI প্রযুক্তি',
    'learnMore.aiDesc': 'আমাদের গভীর শিক্ষণ মডেল লক্ষ লক্ষ উদ্ভিদের ছবিতে প্রশিক্ষিত',
    'learnMore.accuracy': 'নির্ভুলতা এবং গতি',
    'learnMore.accuracyDesc': '৫ সেকেন্ডের কম সময়ে ৯৫%+ শনাক্তকরণের নির্ভুলতা',
    'learnMore.database': 'ব্যাপক ডেটাবেস',
    'learnMore.databaseDesc': 'বিশ্বব্যাপী ১৭,০০০+ উদ্ভিদ প্রজাতি',
    'learnMore.experts': 'বিশেষজ্ঞ যাচাইকরণ',
    'learnMore.expertsDesc': 'পেশাদার উদ্ভিদবিদদের দ্বারা যাচাইকৃত ফলাফল',
    
    // Reviews Page
    'reviews.title': 'ব্যবহারকারীর পর্যালোচনা এবং রেটিং',
    'reviews.subtitle': 'দেখুন উদ্ভিদ প্রেমীরা Plantify AI সম্পর্কে কী বলছেন',
    'reviews.overallRating': 'সামগ্রিক রেটিং',
    'reviews.totalReviews': '৫০,০০০+ পর্যালোচনার ভিত্তিতে',
    'reviews.writeReview': 'একটি পর্যালোচনা লিখুন',
    'reviews.filterAll': 'সব পর্যালোচনা',
    'reviews.filter5Star': '৫ তারকা',
    'reviews.filter4Star': '৪ তারকা',
    'reviews.filter3Star': '৩ তারকা',
    'reviews.ratingBreakdown': 'রেটিং বিভাজন',
    'reviews.verified': 'যাচাইকৃত ক্রয়',
    'reviews.helpful': 'সহায়ক',
    
    // How It Works Page
    'howItWorksPage.title': 'Plantify AI কিভাবে উদ্ভিদ শনাক্ত করে',
    'howItWorksPage.subtitle': 'নির্ভুল উদ্ভিদ শনাক্তকরণ চালিত করে এমন সহজ ৪-ধাপ প্রক্রিয়া আবিষ্কার করুন',
    'howItWorksPage.tryNow': 'এখনই চেষ্টা করুন',
    'howItWorksPage.processTab': 'প্রক্রিয়া',
    'howItWorksPage.technologyTab': 'প্রযুক্তি',
    'howItWorksPage.featuresTab': 'বৈশিষ্ট্য',
    'howItWorksPage.faqTab': 'FAQ',
    'howItWorksPage.step1Title': 'ফটো তুলুন',
    'howItWorksPage.step1Subtitle': 'ক্যাপচার বা আপলোড',
    'howItWorksPage.step1Desc': 'আপনার ক্যামেরা ব্যবহার করে যেকোনো উদ্ভিদের ফটো তুলুন বা গ্যালারি থেকে আপলোড করুন',
    'howItWorksPage.step2Title': 'AI বিশ্লেষণ',
    'howItWorksPage.step2Subtitle': 'উন্নত প্রক্রিয়াকরণ',
    'howItWorksPage.step2Desc': 'আমাদের AI গভীর শিক্ষণ অ্যালগরিদম ব্যবহার করে ছবি বিশ্লেষণ করে',
    'howItWorksPage.step3Title': 'তাৎক্ষণিক ফলাফল',
    'howItWorksPage.step3Subtitle': 'নির্ভুল শনাক্তকরণ',
    'howItWorksPage.step3Desc': 'ব্যাপক উদ্ভিদের তথ্য এবং আত্মবিশ্বাসের স্কোর পান',
    'howItWorksPage.step4Title': 'যত্ন গাইড',
    'howItWorksPage.step4Subtitle': 'বিশেষজ্ঞ পরামর্শ',
    'howItWorksPage.step4Desc': 'বিস্তারিত যত্নের নির্দেশাবলী এবং বৃদ্ধির টিপস পান',
    
    // Features Page
    'featuresPage.title': 'উদ্ভিদ প্রেমীদের জন্য শক্তিশালী বৈশিষ্ট্য',
    'featuresPage.subtitle': 'উদ্ভিদ শনাক্ত, যত্ন এবং শেখার জন্য প্রয়োজনীয় সব উপকরণ আবিষ্কার করুন',
    'featuresPage.tryAllFeatures': 'সব বৈশিষ্ট্য বিনামূল্যে চেষ্টা করুন',
    'featuresPage.comparePlans': 'পরিকল্পনার তুলনা ��রুন',
    'featuresPage.overviewTab': 'পর্যালোচনা',
    'featuresPage.detailedTab': 'বিস্তারিত দৃশ্য',
    'featuresPage.technicalTab': 'প্রযুক্তিগত',
    'featuresPage.comparisonTab': 'পরিকল্পনা',
    'featuresPage.plantIdentification': 'উদ্ভিদ শনাক্তকরণ',
    'featuresPage.personalizedCare': 'ব্যক্তিগতকৃত যত্ন গাইড',
    'featuresPage.diseaseDetection': 'রোগ নির্ণয়',
    'featuresPage.smartReminders': 'স্মার্ট অনুস্মারক',
    'featuresPage.expertCommunity': 'বিশেষজ্ঞ সম্প্রদায়',
    'featuresPage.offlineMode': 'অফলাইন সক্ষমতা',
    
    // Language Selector
    'language.select': 'ভাষা',
    'language.english': 'English',
    'language.hindi': 'हिन्दी',
    'language.bengali': 'বাংলা',
    
    // Sign In Page
    'signIn.title': 'ফিরে আসায় স্বাগতম',
    'signIn.subtitle': 'আপনার Plantify AI অ্যাকাউন্টে সাইন ইন করুন',
    'signIn.emailLabel': 'ইমেইল',
    'signIn.emailPlaceholder': 'আপনার ইমেইল লিখুন',
    'signIn.passwordLabel': 'পাসওয়া���্ড',
    'signIn.passwordPlaceholder': 'আপনার পাসওয়ার্ড লিখুন',
    'signIn.rememberMe': 'আমাকে মনে রাখুন',
    'signIn.signInButton': 'সাইন ইন',
    'signIn.forgotPassword': 'আপনার পাসওয়ার্ড ভুলে গেছেন?',
    'signIn.noAccount': 'কোনো অ্যাকাউন্ট নেই?',
    'signIn.createAccount': 'এখনই একটি তৈরি করুন',
    'signIn.orContinueWith': 'অথবা এর সাথে চালিয়ে যান',
    'signIn.googleSignIn': 'Google দিয়ে চালিয়ে যান',
    'signIn.appleSignIn': 'Apple দিয়ে চালিয়ে যান',
    'signIn.githubSignIn': 'GitHub দিয়ে চালিয়ে যান',
    'signIn.signingIn': 'সাইন ইন হচ্ছে...',
    'signIn.invalidCredentials': 'অবৈধ ইমেইল বা পাসওয়ার্ড',
    'signIn.welcomeBack': 'ফিরে আসায় স্বাগতম!',
    'signIn.backToHome': 'হোমে ফিরুন',

    // Common
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সফলতা',
    'common.cancel': 'বাতিল',
    'common.confirm': 'নিশ্চিত কর��ন',
    'common.save': 'সংরক্ষণ',
    'common.edit': 'সম্পাদনা',
    'common.delete': 'মুছুন',
    'common.close': 'বন্ধ',
    'common.readMore': 'আরও পড়ুন',
    'common.showMore': 'আরও দেখান',
    'common.showLess': 'কম দেখান',
    'common.viewAll': 'সব দেখুন',
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('plantify-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('plantify-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    // Set document language attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};